INHERIT: docs/mkdocs-base.yml

site_name: TinyCTA
site_url: https://tschm.github.io/TinyCTA/
repo_url: https://github.com/tschm/TinyCTA
repo_name: tschm/TinyCTA

docs_dir: docs

nav:
  - Home: index.md
  - API Reference:
      - Signal: api/signal.md
      - Linear Algebra: api/linalg.md
  - Development:
      - Tests: development/TESTS.md
  - CI/CD:
      - coverage: reports/html-coverage/index.html
      - report: reports/html-report/report.html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
