# Workflow for continuous integration testing across multiple platforms and Python versions
name: "CI"
permissions:
  contents: read

# Trigger this workflow on any push to the repository
on:
- push

jobs:
  # Job for running tests on different operating systems and Python versions
  test:
    # The type of runner that the job will run on - determined by the matrix
    runs-on: ${{ matrix.os }}

    # Define a matrix strategy to test multiple configurations
    strategy:
      matrix:
        # Test on Ubuntu, Windows, and macOS
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        # Test on Python 3.10, 3.11, 3.12, and 3.13
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Set up the Python environment with dependencies
      # This step uses the specified Python version from the matrix
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.73
        with:
          python-version: ${{ matrix.python-version }}

      # Step 2: Run tests
      # This step runs pytest to ensure the code works on all platforms and Python versions
      - uses: tschm/cradle/actions/test@v0.1.73
