name: "UPDATE"

on:
  push

permissions:
  contents: write

#inputs:
#  repository:
#    description: 'GitHub repository to download templates from'
#    required: false
#    default: 'tschm/.config-templates'
#  ref:
#    description: 'Branch or tag to download templates from'
#    required: false
#    default: 'v0.3.01'


jobs:
  pre-commit:
    if: github.repository != 'tschm/.config-templates'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: tschm/cradle/actions/updater@v0.3.04