name: "UPDATE"

on:
  push

permissions:
  contents: write


jobs:
  update:
    if: github.repository != 'tschm/.config-templates'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: tschm/cradle/actions/updater@v0.3.04